parameters:
    innmind_provisioner.server.class: Innmind\ProvisionerBundle\Server\Server
    innmind_provisioner.process_status_handler.class: Innmind\ProvisionerBundle\ProcessStatusHandler
    innmind_provisioner.decision_manager.class: Innmind\ProvisionerBundle\DecisionManager
    innmind_provisioner.listener.rabbitmq.class: Innmind\ProvisionerBundle\EventListener\RabbitMQRequirementListener
    innmind_provisioner.listener.provision.class: Innmind\ProvisionerBundle\EventListener\ProvisionListener
    innmind_provisioner.listener.alert.class: Innmind\ProvisionerBundle\EventListener\ProvisionAlertListener
    innmind_provisioner.rabbitmq.queue_history.class: Innmind\ProvisionerBundle\RabbitMQ\QueueHistory
    innmind_provisioner.rabbitmq.admin.class: Innmind\ProvisionerBundle\RabbitMQ\Admin
    innmind_provisioner.alerter.email.class: Innmind\ProvisionerBundle\Alert\EmailAlerter
    innmind_provisioner.alerter.webhook.class: Innmind\ProvisionerBundle\Alert\WebhookAlerter
    innmind_provisioner.http_client.class: GuzzleHttp\Client
    innmind_provisioner.listener.console.class: Innmind\ProvisionerBundle\EventListener\ConsoleListener
    innmind_provisioner.alerter.hipchat.oauth.class: GorkaLaucirica\HipchatAPIv2Client\Auth\OAuth2
    innmind_provisioner.alerter.hipchat.client.class: GorkaLaucirica\HipchatAPIv2Client\Client
    innmind_provisioner.alerter.hipchat.room_api.class: GorkaLaucirica\HipchatAPIv2Client\API\RoomAPI
    innmind_provisioner.alerter.hipchat.class: Innmind\ProvisionerBundle\Alert\HipChatAlerter

services:
    innmind_provisioner.server:
        class: %innmind_provisioner.server.class%
        public: false

    innmind_provisioner.process_status_handler:
        class: %innmind_provisioner.process_status_handler.class%
        public: false
        calls:
            - ['setServer', ['@innmind_provisioner.server']]

    innmind_provisioner.decision_manager:
        class: %innmind_provisioner.decision_manager.class%
        calls:
            - ['setServer', ['@innmind_provisioner.server']]
            - ['setProcessStatusHandler', ['@innmind_provisioner.process_status_handler']]
            - ['setDispatcher', ['@event_dispatcher']]
            - ['setLogger', ['@logger']]

    innmind_provisioner.filesystem:
        class: Symfony\Component\Filesystem\Filesystem
        public: false

    innmind_provisioner.finder:
        class: Symfony\Component\Finder\Finder
        public: false

    innmind_provisioner.rabbitmq.queue_history:
        class: %innmind_provisioner.rabbitmq.queue_history.class%
        public: false
        calls:
            - ['setStoreDirectory', ['%kernel.cache_dir%/innmind_provisioner']]
            - ['setFilesystem', ['@innmind_provisioner.filesystem']]
            - ['setFinder', ['@innmind_provisioner.finder']]

    innmind_provisioner.rabbitmq.admin:
        class: %innmind_provisioner.rabbitmq.admin.class%

    innmind_provisioner.listener.rabbitmq:
        class: %innmind_provisioner.listener.rabbitmq.class%
        calls:
            - ['setProcessStatusHandler', ['@innmind_provisioner.process_status_handler']]
            - ['setQueueHistory', ['@innmind_provisioner.rabbitmq.queue_history']]
            - ['setRabbitMQAdmin', ['@innmind_provisioner.rabbitmq.admin']]
            - ['setLogger', ['@logger']]
        tags:
            - { name: kernel.event_listener, event: innmind_provisioner.compute_requirements, method: handle }

    innmind_provisioner.listener.provision:
        class: %innmind_provisioner.listener.provision.class%
        calls:
            - ['setAppDirectory', ['%kernel.root_dir%']]
        tags:
            - { name: kernel.event_listener, event: innmind_provisioner.provision, method: handle }

    innmind_provisioner.listener.alert:
        class: %innmind_provisioner.listener.alert.class%
        calls:
            - ['setServer', ['@innmind_provisioner.server']]
            - ['setProcessStatusHandler', ['@innmind_provisioner.process_status_handler']]
        tags:
            - { name: kernel.event_listener, event: innmind_provisioner.alert, method: handle }

    innmind_provisioner.alerter.email:
        class: %innmind_provisioner.alerter.email.class%
        public: false
        calls:
            - ['setHost', ['%router.request_context.host%']]

    innmind_provisioner.alerter.webhook:
        class: %innmind_provisioner.alerter.webhook.class%
        public: false
        calls:
            - ['setHttpClient', ['@innmind_provisioner.http_client']]
            - ['setLogger', ['@logger']]

    innmind_provisioner.http_client:
        class: %innmind_provisioner.http_client.class%
        public: false

    innmind_provisioner.listener.console:
        class: %innmind_provisioner.listener.console.class%
        calls:
            - ['setManager', ['@innmind_provisioner.decision_manager']]
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: handle }

    innmind_provisioner.alerter.hipchat.oauth:
        class: %innmind_provisioner.alerter.hipchat.oauth.class%
        public: false
        arguments: [~]

    innmind_provisioner.alerter.hipchat.client:
        class: %innmind_provisioner.alerter.hipchat.client.class%
        public: false
        arguments: ['@innmind_provisioner.alerter.hipchat.oauth']

    innmind_provisioner.alerter.hipchat.room_api:
        class: %innmind_provisioner.alerter.hipchat.room_api.class%
        public: false
        arguments: ['@innmind_provisioner.alerter.hipchat.client']

    innmind_provisioner.alerter.hipchat:
        class: %innmind_provisioner.alerter.hipchat.class%
        calls:
            - ['setRoomApi', ['@innmind_provisioner.alerter.hipchat.room_api']]
